jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Replace placeholders in config
        run: |
          sed -i 's|###urlnotification###|${{ vars.URL_NOTIFICATION }}|g' src/config.json
          sed -i 's|###notificationfunctionkey###|${{ secrets.NOTIFICATION_FUNCTION_KEY }}|g' src/config.json
          sed -i 's|###dashboardUrl###|${{ vars.DASHBOARD_URL }}|g' src/config.json

      - name: Build action
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Run notification action
        uses: ./
        with:
          cydigConfigPath: ${{ github.workspace }}/src/config.json
          slackAccessToken: ${{ secrets.SLACK_TOKEN }}