name: Test notification action
run-name: ${{ github.actor }} is running notification action tests
permissions:
  contents: read
  pages: read
  id-token: write

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout notification action
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Replace placeholders in config
        run: |
          sed -i 's|###urlnotification###|${{ vars.URL_NOTIFICATION }}|g' src/config.json
          sed -i 's|###notificationfunctionkey###|${{ secrets.NOTIFICATION_FUNCTION_KEY }}|g' src/config.json
          sed -i 's|###dashboardUrl###|${{ vars.DASHBOARD_URL }}|g' src/config.json
  
      - name: Build action
        run: npm run build

      # TODO: fix lint errors if we want to use prettier
      #- name: Run lint and prettier
      #  run: npm run lint && npm run format:check

      - name: Run tests
        run: npm test 

      - name: Run notification action
        uses: ./
        with:
          cydigConfigPath: ${{ github.workspace }}/src/cydigConfig.json
          slackAccessToken: ${{ secrets.SLACK_TOKEN }}