name: Test notification action
run-name: ${{ github.actor }} is running notification action tests
permissions:
  contents: read
  pages: read
  id-token: write

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout notification action
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Set dev func URL
        run: |
            echo "dashboardUrl=${{ vars.DASHBOARD_URL }}" >> $GITHUB_ENV
            echo "urlNotification=${{ vars.URL_NOTIFICATION }}" >> $GITHUB_ENV
            echo "updateKey=${{ secrets.NOTIFICATION_FUNCTION_KEY }}" >> $GITHUB_ENV

      - name: Build action
        run: npm run build

      # TODO: fix lint errors if we want to use prettier
      #- name: Run lint and prettier
      #  run: npm run lint && npm run format:check

      - name: Run tests
        run: npm test

      - name: Run notification action
        uses: ./
        with:
          cydigConfigPath: ${{ github.workspace }}/src/cydigConfig.json
          slackAccessToken: ${{ secrets.SLACK_TOKEN }}
