name: Test notification action
run-name: ${{ github.actor }} is running notification action tests
permissions:
  contents: read
  pages: read
  id-token: write

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout notification action
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run lint and prettier
        run: npm run lint && npm run format:check

      - name: Run tests
        run: npm test

      - name: Build action
        run: npm run build

      - name: Run notification action
        uses: ./
        with:      
          # Do we need to add below?
          # PAT-token: ${{ secrets.MY_GITHUB_PAT}}
          # accessTokenAzureDevOps: ${{ secrets.DEVOPS_TOKEN_WORK_ITEMS }}
          cydigConfigPath: ${{ github.workspace }}/src/cydigConfig.json
          slackAccessToken: ${{ secrets.SLACK_TOKEN }}